### PR TITLE
feat: add AWS S3 Support

### PR DESCRIPTION
**Pull request by MattiasMTS**
# What has changed

opening this as a placeholder until I've figured out how to make all the changes work locally.

Let me know if you want me to add Azure blob storage as well. 

Any initial reviews on this draft are 💯  appreciated

### CODE REVIEW

**Comment by IIBenII** [comment]
Hi @MattiasMTS,

Thanks for your PR 🙏 

How do you plan to handle differents backend? Do you plan to add a key in `catalog-info.yaml` / `app-config.yaml` ? or maybe the name of the bucket can be `gcs://` or `s3://`? The best will be to specify a default bucket (GCS or S3) in app-config.yaml and user can overwrite in catalog-info.yaml. 

If you have time / motivation for Azure you are welcome to do it (Maybe in a different PR)

**Comment by MattiasMTS** [comment]
> How do you plan to handle differents backend? Do you plan to add a key in catalog-info.yaml / app-config.yaml ? or maybe the name of the bucket can be gcs:// or s3://

I realized this might be a breaking change depending. I added an interface for the `StorageProvider` (https://github.com/IIBenII/backstage-plugin-dbt/pull/165/files#diff-1572a487e81853b5582abd993eeb09c005a927999a85564113f6ab669b27b166R10) which the user now needs to import (see the updated example in README.md, (https://github.com/IIBenII/backstage-plugin-dbt/pull/165/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R86-R98).

My idea behind this was the following:
1. The bucket is still defined in the `catalog.info.yaml` annotations as `dbtdoc-bucket`
2. You'd now either import the pre-default `StorageProvider` (in this case AWS or GCP) and then handle any suffixes you'd need to do in 1. 

The idea behind 2. is now you can add any of your own cloud provider as long as the interface is fulfilled. Then it is up to the user to define the suffixes needed for the `dbtdoc-bucket` settings.

I also plan to add another PR which should target supporting multiple dbt projects for a monorepo". Because as of now, you are limited to one dbt project per entity, right?

**Comment by IIBenII** [comment]
Got it for the import. It's good but need that all dbt doc are in the same backend technology (GCS only or S3 only). With the idea of specify the type of storage and use the right one, we can have differents backend. I'm not sure if it's needed, so we can keep as you propose.

For your monorepo remark, I'm not aware of using Backstage with a monorepo. If you have multiple backstage entity, you can have multiple dbt project even if it's in a monorepo. But if your use case is a monorepo as one Backstage entity but handling multiple dbt project, then yes this plugin doesn't support it. But I'm not sure if this usage of 1 entity for multiple dbt project is a good idea, as backstage entity also give you owners, systems etc. associate with your entity.

**Comment by MattiasMTS** [comment]
Should be ready for review now. I'm happy to add any "publisher" type in the metadata (similar to how techdocs have on "publisher type" azureBlobStorage, awsS3, etc.)

Let me know what you think @IIBenII !

**Review by IIBenII — APPROVED** [review]
LGTM thanks a lot

**Pull request merged**
